### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by WGroleau** [Sh1d0w/clean-links#17]
![CleanLinks](https://user-images.githubusercontent.com/5910274/123862522-48760c00-d8dd-11eb-97cb-61c9d1301bbe.jpg)

**Comment by Sh1d0w** [comment]
https://support.apple.com/en-gb/HT202491

This is because I've packaged this with my personal developer profile, which is a free one (haven't purchased to verify it).

You need to right click on the app and then click open for the first time, this is restriction from Apple.

If you wish you can also download the code from this repo and compile it by yourself with XCode using your own developer ID.

**Comment by WGroleau** [comment]
I didn't recognize what to do because Apple changed the warning (used to be "unidentified developer").  So it's in there now.  I also tried building it myself, but tried five different way and  XCode said "build failed" each time.
