### ISSUE TITLE
How do we tell if this is working?

### ISSUE THREAD

**Issue by chmac** [Sh1d0w/clean-links#18]
I tried installing this, activated both plugins, opened dev tools, set network to preserve the log, then copied & pasted a tracking link. It looks like `l.facebook.com` was still loaded first. I also tried clicking a link directly and I saw a redirect flash in the address bar, but too quick to know what it was.

Is there any way to know if this plugin is really working?

Would it be crazy to add a "confirmation mode" that pops a `window.confirm()` asking if the user wants to follow a link? It'd make privacy nerds like me happy, but might be overly complicated and unnecessary for most folks.

**Comment by Sh1d0w** [comment]
Hey @chmac,

The way the plugin works is that it uses Safari's extension framework to [intercept](https://github.com/Sh1d0w/clean-links/blob/master/Clean%20Links%20Extension/SafariExtensionHandler.swift#L90) each navigation initiated in the browser. Then it checks if we should clean / rewrite the url and if so we initiate new navigation to the clean url (without any tracking params).

I guess that seems like tricky behaviour because of that flash, but that's what we have access to as a Safari extension. I guess one way to verify it works correctly is to route your traffic through any proxy like Charles and see the outgoing requests logged there. 

Thanks for using the extension. Let me know if you have more questions.

**Comment by chmac** [comment]
Thanks for the info. Just to check I understood correctly, the request will look like normal in the dev tools, but it's actually being intercepted and redirected?

Okay, sounds cool. Would be neat if there was a log or alert type system to be able to verify. It's hard for me to know if it's enabled and working without routing everything through a proxy I guess...

**Comment by chmac** [comment]
Also, forgot to say in my first message, thanks for this plugin, it's awesome!
