### ISSUE TITLE
Toolbar button enhancements request

### ISSUE THREAD

**Issue by gkarag** [Sh1d0w/clean-links#5]
Having as examples other content blocker plugins, I would request to show the number of the removed trackers and stats for the current page instead of the complete count. Maybe have a log feature for all the removed trackers in case you consider it relevant.
Also the toolbar button shows tooltip "Your button" on mouse hover.

**Comment by Sh1d0w** [comment]
Thanks for the report. I've just published a new release that fixes the label issue.

Regarding the count and the number of the trackers blocked - it currently shows the total amount of links that were cleaned out from tracking params.

This plugin primary goal is not to be actually a content blocker, although it does some content blocking on FB in order to avoid background tracking. It uses Safari's native [Content Blocker](https://developer.apple.com/documentation/safariservices/creating_a_content_blocker) API, which unfortunately does not provide feedback on what and when it was blocked back to the plugin.
